export const data = [
  {
    _id: 1,
    name: 'Beautiful Things',
    author: 'Benson Boone',
    release_date: '2024-01-01',
    genre: ['Поп', 'Баллада'],
    duration_in_seconds: 205,
    album: 'Beautiful Things',
    logo: null,
    track_file: 'https://example.com/track1.mp3',
    stared_user: [],
  },
  {
    _id: 2,
    name: 'Adivino',
    author: 'Myke Towers, Bad Bunny',
    release_date: '2024-02-01',
    genre: ['Латино', 'Хип-хоп'],
    duration_in_seconds: 220,
    album: 'Adivino',
    logo: null,
    track_file: 'https://example.com/track2.mp3',
    stared_user: [],
  },
  {
    _id: 3,
    name: 'Britpop',
    author: 'A.G. Cook',
    release_date: '2024-03-01',
    genre: ['Электронная', 'Гиперпоп'],
    duration_in_seconds: 180,
    album: 'Britpop',
    logo: null,
    track_file: 'https://example.com/track3.mp3',
    stared_user: [],
  },
  {
    _id: 4,
    name: 'XO (Only if You Say Yes)',
    author: 'ENHYPEN',
    release_date: '2024-04-01',
    genre: ['K-pop'],
    duration_in_seconds: 195,
    album: 'XO',
    logo: null,
    track_file: 'https://example.com/track4.mp3',
    stared_user: [],
  },
  {
    _id: 5,
    name: 'After Hours',
    author: 'Kehlani',
    release_date: '2024-05-01',
    genre: ['R&B'],
    duration_in_seconds: 210,
    album: 'After Hours',
    logo: null,
    track_file: 'https://example.com/track5.mp3',
    stared_user: [],
  },
  {
    _id: 6,
    name: 'On the Game',
    author: 'The Black Keys',
    release_date: '2024-06-01',
    genre: ['Рок'],
    duration_in_seconds: 245,
    album: 'Ohio Players',
    logo: null,
    track_file: 'https://example.com/track6.mp3',
    stared_user: [],
  },
  {
    _id: 7,
    name: 'Big Dawgs',
    author: 'Hanumankind feat. Kalmi',
    release_date: '2024-07-01',
    genre: ['Хип-хоп'],
    duration_in_seconds: 230,
    album: 'Big Dawgs',
    logo: null,
    track_file: 'https://example.com/track7.mp3',
    stared_user: [],
  },
  {
    _id: 8,
    name: 'In Front of Me Now',
    author: 'Nada Surf',
    release_date: '2024-08-01',
    genre: ['Инди-рок'],
    duration_in_seconds: 215,
    album: 'Moon Mirror',
    logo: null,
    track_file: 'https://example.com/track8.mp3',
    stared_user: [],
  },
  {
    _id: 9,
    name: 'That’s My Floor',
    author: 'Magdalena Bay',
    release_date: '2024-09-01',
    genre: ['Синти-поп'],
    duration_in_seconds: 200,
    album: 'Imaginal Disk',
    logo: null,
    track_file: 'https://example.com/track9.mp3',
    stared_user: [],
  },
  {
    _id: 10,
    name: 'Von dutch',
    author: 'Charli XCX',
    release_date: '2024-10-01',
    genre: ['Поп'],
    duration_in_seconds: 190,
    album: 'Brat',
    logo: null,
    track_file: 'https://example.com/track10.mp3',
    stared_user: [],
  },
  {
    _id: 11,
    name: 'A Bar Song (Tipsy)',
    author: 'Shaboozey',
    release_date: '2024-11-01',
    genre: ['Кантри', 'Рэп'],
    duration_in_seconds: 225,
    album: 'A Bar Song (Tipsy)',
    logo: null,
    track_file: 'https://example.com/track11.mp3',
    stared_user: [],
  },
  {
    _id: 12,
    name: 'Nasty',
    author: 'Tinashe',
    release_date: '2024-12-01',
    genre: ['R&B'],
    duration_in_seconds: 210,
    album: 'Nasty',
    logo: null,
    track_file: 'https://example.com/track12.mp3',
    stared_user: [],
  },
  {
    _id: 13,
    name: 'Not Like Us',
    author: 'Kendrick Lamar',
    release_date: '2024-05-01',
    genre: ['Хип-хоп'],
    duration_in_seconds: 260,
    album: 'Not Like Us',
    logo: null,
    track_file: 'https://example.com/track13.mp3',
    stared_user: [],
  },
  {
    _id: 14,
    name: 'Fortnight',
    author: 'Taylor Swift',
    release_date: '2024-04-01',
    genre: ['Поп'],
    duration_in_seconds: 240,
    album: 'The Tortured Poets Department',
    logo: null,
    track_file: 'https://example.com/track14.mp3',
    stared_user: [],
  },
  {
    _id: 15,
    name: 'Espresso',
    author: 'Sabrina Carpenter',
    release_date: '2024-03-01',
    genre: ['Поп'],
    duration_in_seconds: 195,
    album: 'Espresso',
    logo: null,
    track_file: 'https://example.com/track15.mp3',
    stared_user: [],
  },
  {
    _id: 16,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    _id: 17,
    name: 'Open Sea epic',
    author: 'Frank Schroter',
    release_date: '2019-06-12',
    genre: ['Классическая музыка'],
    duration_in_seconds: 165,
    album: 'Open Sea epic',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Frank_Schroter_-_Open_Sea_epic.mp3',
    stared_user: [],
  },
  {
    _id: 18,
    name: 'Sneaky Snitch',
    author: 'Kevin Macleod',
    release_date: '2022-04-16',
    genre: ['Классическая музыка'],
    duration_in_seconds: 305,
    album: 'Sneaky Snitch',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_Macleod_-_Sneaky_Snitch.mp3',
    stared_user: [],
  },
  {
    _id: 19,
    name: 'Secret Garden',
    author: 'Mixkit',
    release_date: '1972-06-06',
    genre: ['Классическая музыка'],
    duration_in_seconds: 324,
    album: 'Secret Garden',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Mixkit_-_Secret_Garden.mp3',
    stared_user: [],
  },

  {
    _id: 20,
    name: 'A journey of successfull winners',
    author: '-',
    release_date: '1985-02-02',
    genre: ['Классическая музыка'],
    duration_in_seconds: 255,
    album: '-',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Musiclfiles_-_A_Journey_For_Successful_Winners.mp3',
    stared_user: [],
  },
  {
    _id: 21,
    name: 'Epic Heroic Conquest',
    author: '-',
    release_date: '1962-01-15',
    genre: ['Классическая музыка'],
    duration_in_seconds: 200,
    album: 'Epic Heroic Conquest',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Musiclfiles_-_Epic_Heroic_Conquest.mp3',
    stared_user: [],
  },
  {
    _id: 22,
    name: 'The March OF The Final Battle',
    author: '-',
    release_date: '2011-11-02',
    genre: ['Классическая музыка'],
    duration_in_seconds: 206,
    album: 'The March OF The Final Battle',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/musiclfiles_-_The_March_Of_The_Final_Battle.mp3',
    stared_user: [],
  },
  {
    _id: 23,
    name: 'True Summer',
    author: '-',
    release_date: '2012-06-01',
    genre: ['Классическая музыка'],
    duration_in_seconds: 253,
    album: 'True Summer',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Musiclfiles_-_True_Summer.mp3',
    stared_user: [],
  },
  {
    _id: 24,
    name: 'Background Sensible',
    author: 'Waltz Piano',
    release_date: '2003-05-12',
    genre: ['Классическая музыка'],
    duration_in_seconds: 135,
    album: 'Background Sensible',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Waltz_Piano_-_Background_Sensible.mp3',
    stared_user: [],
  },
  {
    _id: 25,
    name: 'Cinematic',
    author: 'Winniethemoog',
    release_date: '2004-10-01',
    genre: ['Классическая музыка'],
    duration_in_seconds: 206,
    album: 'Cinematic',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Winniethemoog_-_Action_Sport_Breakbeat.mp3',
    stared_user: [],
  },
];
